name: workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update && sudo apt-get install -y cmake
      - run: mkdir build && cmake -B build -S . && cmake --build build
      - uses: actions/upload-artifact@v4
        with:
          name: bin
          path: |
            build/main
            build/tests
            build/rm

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: bin
      - run: chmod +x tests && ./tests

  run:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: bin
      - run: chmod +x main && ./main 2 7

  benchmark:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: bin
      - run: chmod +x bm && ./bm
